### ISSUE TITLE
Get the authenticated GitHub App should use "bearer" auth

### ISSUE THREAD

**Issue by swinton** [gr2m/octokit.rest#47]
Thanks for this great tool! :bow:

I noticed an issue I think, with [`GET /app`](https://octokit.rest/GET/app).

This page uses `authorization: token $JWT` as a header value, but I believe it should use `authorization: bearer $JWT` instead.

Currently, it returns an error: `A JSON web token could not be decoded`.

**Comment by swinton** [comment]
It seems like it would be OK to just replace `token` with `bearer` in these two files: 

https://github.com/gr2m/octokit.rest/blob/03bb6f6bedb4e91b7fa018cfcf06f5ccfdac2696/api/detail.js#L100

https://github.com/gr2m/octokit.rest/blob/03bb6f6bedb4e91b7fa018cfcf06f5ccfdac2696/public/detail.js#L24

I _think_ `bearer` is more appropriate here, since the tokens will typically be "access tokens" and so should conform to [the OAuth 2.0 spec for the request header field](https://tools.ietf.org/html/rfc6750#section-2.1).

**Comment by gr2m** [comment]
today I learned! I didn't know that the `bearer ` prefix can be used for other endpoints than the ones requiring the JWT authentication!

**Comment by gr2m** [comment]
related: our idea is to built-in means of authentication. I will work on an OAuth Web Flow login for oauth access tokens, but we could also provide a "GitHub App Login" with a form where you enter the private key and app ID, and an optional installation ID which could be a pre-populated select ... I wish I had more time to hack on this :D

**Comment by swinton** [comment]
> we could also provide a "GitHub App Login" with a form where you enter the private key and app ID, and an optional installation ID which could be a pre-populated select

I would loooooove this. This would be extremely useful for workshops on GitHub Apps, for example.



> I wish I had more time to hack on this :D

Same. I would love to pitch in.

**Comment by gr2m** [comment]
I'll keep you posted :)
